### ISSUE TITLE
Gallery not showing when hosted on Netlify

### ISSUE THREAD

**Issue by amresha** [okslutsiv/gatsby-image-lightbox#1]
I used this example for my personal gatsby blog, It's working locally but not displaying the photo gallery when I hosted on Netlify. Can you please check what I am doing wrong.

**My Repo:** https://github.com/amresha/amresha-official
**Netlify Hosted:** https://amresha.netlify.app/PhotoCollection
**Local Screenshot:** 
![image](https://user-images.githubusercontent.com/66923948/88152393-9f269080-cc0c-11ea-9fb9-1b35bb90b072.png)

**Comment by okslutsiv** [comment]
hi, Amresha, looks like the problem is with you paths. Gatsby can find the folder on your machine  with absolutePath: {regex: "E:/amresha/amresha/src/images/gallery/"}} but not on the Netlify server. Try shorten the regex to "/images/gallery/", it can help. Also I see the problem with image sourced from "./photocollection-header.jpg". You should either move it to the static folder or import as described here: https://www.gatsbyjs.org/docs/importing-assets-into-files/. Hope this helps

**Comment by okslutsiv** [comment]
ps. Looks like lightbox-react is not supported currently. Pity

**Comment by amresha** [comment]
thanks a lot, @okslutsiv for your guidance :) I have updated the regex path to  ".src/images/gallery/" and it's working now 👍 . I will look into the link as well for importing a sourced image.

**Comment by okslutsiv** [comment]
glad to help @amresha
